---
model:
  type: DGAKT
  latent_dims:
    - 32
    - 32
  in_efeats: 3
  parameters: dgakt_ednet_part_b_0.7844.pt

dataset:
  name: ednet_part_b
  max_seq: 64

train:
  learning_rates:
    - 4e-3 
  epochs: 20
  batch_size: 64
  gamma: 0.75
  lambda: 0.001
