---
model:
  type: DGAKT
  latent_dims:
    - 32
    - 32
  in_efeats: 3
  out_efeats: 3
  parameters: dgakt_assist_part_b_0.9486.pt

dataset:
  name: assist_part_b
  max_seq: 64

train:
  learning_rates:
    - 4e-3 
  epochs: 20
  batch_size: 64
  gamma: 0.75
  lambda: 0.001
