---
key: dgkt_ednet_64_test
model:
  type: DGKT
  latent_dims:
    - 32
    - 32
  in_efeats: 3
  parameters: dgkt_ednet_64_0.8186.pt


dataset:
  name: ednet
  max_seq: 64

train:
  batch_size: 256
  gamma: 0.75
  lambda: 0.001
