---
model:
  type: IGMC
  num_relations: 4
  latent_dims:
    - 32
    - 32
    - 32
    - 32
  edge_dropout: 0.
  parameters: igmc_ednet_64_b_0.7611.pt

dataset:
  name: ednet_part_b
  max_seq: 64

train:
  learning_rates:
    - 1e-3
  epochs: 20
  batch_size: 256
