---
model:
  type: DAGKT
  hop: 1
  num_relations: 4
  latent_dims:
    - 32
    - 32
  edge_dropout: 0.

dataset:
  name: junyi
  max_seq: 64

train:
  batch_size: 128
  learning_rates:
    - 1e-3
  weight_decay: 0.0
  lr_decay_step: 5
  lr_decay_factor: 0.98
  log_interval: 100
  log_dir: log
  gamma: 0.75
  lambda: 0.003
