---
key: igmc_assist_64_assist_part_a
model:
  type: IGMC
  num_relations: 4
  latent_dims:
    - 32
    - 32
    - 32
    - 32
  edge_dropout: 0.

dataset:
  name: assist_part_a
  max_seq: 64

train:
  device: 0
  epochs: 20
  batch_size: 128
  weight_decay: 0.0
  lr_decay_step: 5
  lr_decay_factor: 0.98
  log_interval: 100
  log_dir: log
