files:
  # - ./train_configs/dgakt_assist_64.yaml
  # - ./train_configs/dgakt_ednet_64.yaml
  # - ./train_configs/dgakt_junyi_64.yaml
  # - ./train_configs/igmc_assist_64.yaml
  - ./train_configs/igmc_ednet_64.yaml
  # - ./train_configs/igmc_junyi_64.yaml

  # - ./train_configs/dgakt_assist_64_a.yaml
  # - ./train_configs/dgakt_assist_64_b.yaml
  # - ./train_configs/dgakt_assist_64_c.yaml

  # - ./train_configs/igmc_assist_64_a.yaml
  # - ./train_configs/igmc_assist_64_b.yaml
  # - ./train_configs/igmc_assist_64_c.yaml

  # - ./train_configs/dgakt_ednet_64_a.yaml
  # - ./train_configs/dgakt_ednet_64_b.yaml
  # - ./train_configs/dgakt_ednet_64_c.yaml

  # - ./train_configs/igmc_ednet_64_a.yaml
  # - ./train_configs/igmc_ednet_64_b.yaml
  # - ./train_configs/igmc_ednet_64_c.yaml


