device = "cuda"
# device = "cpu"
# MAX_SEQ = 128
EMBED_DIMS = 32
ENC_HEADS = DEC_HEADS = 4
NUM_ENCODER = NUM_DECODER = 6
BATCH_SIZE = 128
QUESTIONS_FILE = "data/questions.csv"
DROPOUT = 0.2
EPOCHS = 20
NUM_WORKS = 16
ASSIST_EXE = 3162
EDNET_EXE = 13523
IN_FEATS = 6
LAMBDA_LOSS = 0.001
# USE_CENTER_NODE = True
